name: Build Docker images

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - '.github/workflows/docker.yml'
      - 'bookworm/**'
  pull_request:
    paths:
      - '.github/workflows/docker.yml'
      - 'bookworm/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

permissions:
  contents: write
  packages: write

jobs:
  docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push base image
        id: build_base
        uses: docker/build-push-action@v5
        with:
          context: ./bookworm
          file: ./bookworm/Dockerfile
          target: bookworm-base
          tags: |
            ${{ env.REGISTRY_IMAGE }}:latest
            ${{ env.REGISTRY_IMAGE }}:base
          push: true
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }}:latest

      - name: Build and push metamod image
        id: build_metamod
        uses: docker/build-push-action@v5
        with:
          context: ./bookworm
          file: ./bookworm/Dockerfile
          target: bookworm-metamod
          tags: ${{ env.REGISTRY_IMAGE }}:metamod
          push: true
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }}:metamod

      - name: Build and push sourcemod image
        id: build_sourcemod
        uses: docker/build-push-action@v5
        with:
          context: ./bookworm
          file: ./bookworm/Dockerfile
          target: bookworm-sourcemod
          tags: ${{ env.REGISTRY_IMAGE }}:sourcemod
          push: true
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }}:sourcemod

      - name: Image digests
        run: |
          echo "Base image digest: ${{ steps.build_base.outputs.digest }}"
          echo "Metamod image digest: ${{ steps.build_metamod.outputs.digest }}"
          echo "Sourcemod image digest: ${{ steps.build_sourcemod.outputs.digest }}"
